#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""翻译所有未翻译的参数描述"""

import json

# 参数名称到中文描述的映射
PARAM_TRANSLATIONS = {
    # 通用参数
    "event": "事件数据",
    "arg1": "参数1",
    "arg2": "参数2",
    "arg3": "参数3",
    "arg4": "参数4",
    "arg5": "参数5",
    "arg6": "参数6",
    "arg7": "参数7",
    "arg8": "参数8",
    "arg9": "参数9",
    "arg10": "参数10",
    "name": "名称",
    "value": "值",
    "index": "索引",
    "key": "键",
    "data": "数据",
    "info": "信息",
    "context": "上下文",
    "callback": "回调函数",
    "callbackInfo": "回调信息",
    "handle": "句柄",
    "entity": "实体",
    "unit": "单位",
    "source": "来源",
    "result": "结果",
    "params": "参数表",
    "options": "选项",
    "flags": "标志位",
    "type": "类型",
    "count": "数量",
    "amount": "数量",
    "time": "时间",
    "duration": "持续时间",
    "delay": "延迟",
    "interval": "间隔",
    "rate": "速率",
    "speed": "速度",
    "distance": "距离",
    "radius": "半径",
    "range": "范围",
    "height": "高度",
    "width": "宽度",
    "scale": "缩放",
    "angle": "角度",
    "direction": "方向",
    "position": "位置",
    "location": "位置",
    "origin": "原点",
    "target": "目标",
    "destination": "目的地",
    "start": "起点",
    "end": "终点",
    "min": "最小值",
    "max": "最大值",
    "level": "等级",
    "tier": "层级",
    "priority": "优先级",
    "weight": "权重",
    "chance": "几率",
    "percentage": "百分比",
    "ratio": "比例",
    "factor": "因子",
    "multiplier": "乘数",
    "bonus": "加成",
    "modifier": "修饰器",
    "buff": "增益",
    "debuff": "减益",
    "effect": "效果",
    "state": "状态",
    "mode": "模式",
    "phase": "阶段",
    "stage": "阶段",
    "step": "步骤",
    "enabled": "是否启用",
    "disabled": "是否禁用",
    "active": "是否激活",
    "visible": "是否可见",
    "hidden": "是否隐藏",
    "valid": "是否有效",
    "success": "是否成功",
    "failed": "是否失败",
    "error": "错误",
    "message": "消息",
    "text": "文本",
    "label": "标签",
    "title": "标题",
    "description": "描述",
    "tooltip": "提示",
    "color": "颜色",
    "alpha": "透明度",
    "r": "红色分量",
    "g": "绿色分量",
    "b": "蓝色分量",
    "x": "X坐标",
    "y": "Y坐标",
    "z": "Z坐标",
    "pitch": "俯仰角",
    "yaw": "偏航角",
    "roll": "翻滚角",
    
    # DOTA2 特定参数
    "playerId": "玩家ID",
    "playerID": "玩家ID",
    "player": "玩家",
    "heroId": "英雄ID",
    "hero": "英雄",
    "npc": "NPC单位",
    "ability": "技能",
    "abilityName": "技能名称",
    "abilityIndex": "技能索引",
    "item": "物品",
    "itemName": "物品名称",
    "itemIndex": "物品索引",
    "slot": "槽位",
    "caster": "施法者",
    "attacker": "攻击者",
    "inflictor": "伤害来源",
    "victim": "受害者",
    "killer": "击杀者",
    "owner": "所有者",
    "parent": "父级",
    "child": "子级",
    "modifierName": "修饰器名称",
    "modifierTable": "修饰器表",
    "activity": "动作类型",
    "gesture": "手势",
    "animation": "动画",
    "sound": "音效",
    "particle": "粒子特效",
    "particleName": "粒子名称",
    "effectName": "特效名称",
    "modelName": "模型名称",
    "scriptName": "脚本名称",
    "className": "类名",
    "teamNumber": "队伍编号",
    "team": "队伍",
    "damage": "伤害",
    "damageType": "伤害类型",
    "damageFlags": "伤害标志",
    "health": "生命值",
    "mana": "法力值",
    "armor": "护甲",
    "gold": "金钱",
    "xp": "经验值",
    "experience": "经验值",
    "bounty": "赏金",
    "cooldown": "冷却时间",
    "manaCost": "法力消耗",
    "castPoint": "施法前摇",
    "castRange": "施法距离",
    "attackRange": "攻击距离",
    "attackSpeed": "攻击速度",
    "moveSpeed": "移动速度",
    "turnRate": "转身速率",
    "vision": "视野",
    "visionRange": "视野范围",
    "dayVision": "白天视野",
    "nightVision": "夜间视野",
    "projectile": "弹道",
    "projectileSpeed": "弹道速度",
    "criticalStrike": "暴击",
    "evasion": "闪避",
    "accuracy": "命中",
    "lifesteal": "吸血",
    "spellLifesteal": "技能吸血",
    "magicResist": "魔法抗性",
    "statusResist": "状态抗性",
    "regen": "恢复",
    "healthRegen": "生命恢复",
    "manaRegen": "法力恢复",
    
    # 布尔参数
    "bEnabled": "是否启用",
    "bVisible": "是否可见",
    "bHidden": "是否隐藏",
    "bActive": "是否激活",
    "bValid": "是否有效",
    "bSuccess": "是否成功",
    "bImmediate": "是否立即",
    "bForce": "是否强制",
    "bSilent": "是否静默",
    "bNoSpectators": "是否无观众",
    "bPlaySound": "是否播放音效",
    "bShowEffect": "是否显示特效",
    "reincarnate": "是否复活",
    "lethal": "是否致命",
    "physical": "是否物理",
    "magical": "是否魔法",
    "pure": "是否纯粹",
    "ignoreInvis": "是否忽略隐身",
    "ignoreArmor": "是否忽略护甲",
    "ignoreMagicImmunity": "是否忽略魔免",
    "useProjectile": "是否使用弹道",
    "useCastAttackOrb": "是否使用法球",
    "processProcs": "是否触发特效",
    "skipCooldown": "是否跳过冷却",
    "fakeAttack": "是否假攻击",
    "neverMiss": "是否必中",
    "activated": "是否激活",
    "channeling": "是否持续施法",
    "stealable": "是否可偷取",
    "stolen": "是否被偷取",
    "frozenCooldown": "是否冻结冷却",
    "inAbilityPhase": "是否在技能阶段",
    "refCounts": "是否引用计数",
    "upgradeRecommended": "是否推荐升级",
    "supressSpeech": "是否抑制语音",
    "useHealth": "是否使用生命值",
    "removePositive": "是否移除正面效果",
    "removeNegative": "是否移除负面效果",
    "removeStuns": "是否移除眩晕",
    "removeExceptions": "是否移除例外",
    "frameOnly": "是否仅帧",
    
    # 其他参数
    "charges": "充能次数",
    "stacks": "层数",
    "criteriaTable": "条件表",
    "ignoreTempAttackSpeed": "是否忽略临时攻速",
    "skin": "皮肤索引",
    "meshGroupMask": "网格组掩码",
    "materialGroup": "材质组",
    "sequence": "序列",
    "cycle": "循环",
    "playbackRate": "播放速率",
    "fadeTime": "淡化时间",
    "extraData": "额外数据",
    "userData": "用户数据",
    "customData": "自定义数据",
    "eventData": "事件数据",
    "gameEvent": "游戏事件",
    "filterTable": "过滤表",
    "searchType": "搜索类型",
    "findType": "查找类型",
    "orderType": "命令类型",
    "damageCategory": "伤害类别",
    "abilitySpecialName": "技能特殊值名称",
    "abilitySpecialLevel": "技能特殊值等级",
    "additionalFlags": "附加标志",
    "healthAmount": "生命值数量",
    "vcd": "VCD文件",
    "vcdFile": "VCD文件路径",
    "modelScale": "模型缩放",
    "offset": "偏移量",
    "padding": "边距",
    "margin": "外边距",
    "spacing": "间距",
    "gap": "间隙",
    "thickness": "厚度",
    "length": "长度",
    "size": "大小",
    "capacity": "容量",
    "limit": "限制",
    "threshold": "阈值",
    "tolerance": "容差",
    "precision": "精度",
    "accuracy": "准确度",
    "quality": "质量",
    "intensity": "强度",
    "strength": "强度/力量",
    "power": "力量",
    "force": "力",
    "mass": "质量",
    "volume": "体积",
    "area": "面积",
    "surface": "表面",
    "normal": "法线",
    "tangent": "切线",
    "curve": "曲线",
    "path": "路径",
    "route": "路线",
    "waypoint": "路点",
    "checkpoint": "检查点",
    "spawnPoint": "出生点",
    "respawnTime": "复活时间",
    "deathTime": "死亡时间",
    "killTime": "击杀时间",
    "startTime": "开始时间",
    "endTime": "结束时间",
    "gameTime": "游戏时间",
    "realTime": "真实时间",
    "deltaTime": "时间增量",
    "frameTime": "帧时间",
    "tickRate": "Tick速率",
    "frameRate": "帧率",
    "updateRate": "更新速率",
    "refreshRate": "刷新率",
}

def translate_params():
    # 读取文件
    with open('data/luaapi/classes_cn.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    translated_count = 0
    still_empty = []
    
    for item in data['items']:
        for method in item.get('methods', []):
            for param in method.get('parameters', []):
                if not param.get('description_cn') or param['description_cn'].strip() == '':
                    param_name = param['name']
                    
                    # 尝试查找翻译
                    if param_name in PARAM_TRANSLATIONS:
                        param['description_cn'] = PARAM_TRANSLATIONS[param_name]
                        translated_count += 1
                    else:
                        # 尝试驼峰命名转换
                        lower_name = param_name.lower()
                        found = False
                        for key, value in PARAM_TRANSLATIONS.items():
                            if key.lower() == lower_name:
                                param['description_cn'] = value
                                translated_count += 1
                                found = True
                                break
                        
                        if not found:
                            # 根据参数名生成默认描述
                            param['description_cn'] = generate_description(param_name)
                            translated_count += 1
    
    # 保存文件
    with open('data/luaapi/classes_cn.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"翻译了 {translated_count} 个参数")

def generate_description(param_name):
    """根据参数名自动生成描述"""
    # 处理常见前缀
    prefixes = {
        'b': '是否',
        'n': '',
        'f': '',
        'i': '',
        's': '',
        'h': '',
        'p': '',
        'v': '',
    }
    
    # 驼峰转空格分隔
    import re
    words = re.sub('([A-Z])', r' \1', param_name).strip().split()
    
    # 常见单词翻译
    word_map = {
        'ability': '技能',
        'item': '物品',
        'unit': '单位',
        'hero': '英雄',
        'player': '玩家',
        'team': '队伍',
        'target': '目标',
        'source': '来源',
        'caster': '施法者',
        'attacker': '攻击者',
        'victim': '受害者',
        'damage': '伤害',
        'health': '生命值',
        'mana': '法力值',
        'gold': '金钱',
        'speed': '速度',
        'range': '范围',
        'duration': '持续时间',
        'cooldown': '冷却时间',
        'modifier': '修饰器',
        'buff': '增益',
        'effect': '效果',
        'particle': '粒子',
        'sound': '音效',
        'model': '模型',
        'animation': '动画',
        'position': '位置',
        'location': '位置',
        'direction': '方向',
        'angle': '角度',
        'radius': '半径',
        'height': '高度',
        'width': '宽度',
        'scale': '缩放',
        'time': '时间',
        'delay': '延迟',
        'interval': '间隔',
        'count': '数量',
        'index': '索引',
        'id': 'ID',
        'name': '名称',
        'type': '类型',
        'value': '值',
        'flag': '标志',
        'state': '状态',
        'mode': '模式',
        'level': '等级',
        'attack': '攻击',
        'cast': '施法',
        'move': '移动',
        'vision': '视野',
        'armor': '护甲',
        'magic': '魔法',
        'physical': '物理',
        'projectile': '弹道',
        'event': '事件',
        'callback': '回调',
        'context': '上下文',
        'data': '数据',
        'info': '信息',
        'table': '表',
        'list': '列表',
        'array': '数组',
        'string': '字符串',
        'number': '数值',
        'boolean': '布尔值',
        'function': '函数',
        'entity': '实体',
        'handle': '句柄',
        'script': '脚本',
        'file': '文件',
        'path': '路径',
        'spawn': '生成',
        'create': '创建',
        'destroy': '销毁',
        'remove': '移除',
        'add': '添加',
        'set': '设置',
        'get': '获取',
        'update': '更新',
        'refresh': '刷新',
        'reset': '重置',
        'clear': '清除',
        'start': '开始',
        'stop': '停止',
        'end': '结束',
        'begin': '开始',
        'finish': '完成',
        'complete': '完成',
        'success': '成功',
        'fail': '失败',
        'error': '错误',
        'warning': '警告',
        'message': '消息',
        'text': '文本',
        'label': '标签',
        'title': '标题',
        'color': '颜色',
        'alpha': '透明度',
        'red': '红色',
        'green': '绿色',
        'blue': '蓝色',
        'min': '最小',
        'max': '最大',
        'initial': '初始',
        'final': '最终',
        'current': '当前',
        'previous': '上一个',
        'next': '下一个',
        'first': '第一个',
        'last': '最后一个',
        'all': '全部',
        'any': '任意',
        'none': '无',
        'default': '默认',
        'custom': '自定义',
        'special': '特殊',
        'unique': '唯一',
        'temp': '临时',
        'permanent': '永久',
        'ignore': '忽略',
        'skip': '跳过',
        'force': '强制',
        'silent': '静默',
        'immediate': '立即',
        'instant': '瞬间',
        'Arg': '参数',
    }
    
    translated_words = []
    for word in words:
        lower_word = word.lower()
        if lower_word in word_map:
            translated_words.append(word_map[lower_word])
        else:
            translated_words.append(word)
    
    result = ''.join(translated_words)
    
    # 如果没有翻译，返回原名
    if result == param_name:
        return param_name + "参数"
    
    return result

if __name__ == '__main__':
    translate_params()
