# Panorama API URLs - 共48个
PANORAMA_API_URLS = [
    "https://moddota.com/api/#!/panorama/api/ABILITY_TYPES",
    "https://moddota.com/api/#!/panorama/api/AbilityLearnResult_t",
    "https://moddota.com/api/#!/panorama/api/Attributes",
    "https://moddota.com/api/#!/panorama/api/CLICK_BEHAVIORS",
    "https://moddota.com/api/#!/panorama/api/DAMAGE_TYPES",
    "https://moddota.com/api/#!/panorama/api/DOTAAbilitySpeakTrigger_t",
    "https://moddota.com/api/#!/panorama/api/DOTAConnectionState_t",
    "https://moddota.com/api/#!/panorama/api/DOTADamageFlag_t",
    "https://moddota.com/api/#!/panorama/api/DOTAInventoryFlags_t",
    "https://moddota.com/api/#!/panorama/api/DOTAKeybindCommand_t",
    "https://moddota.com/api/#!/panorama/api/DOTALimits_t",
    "https://moddota.com/api/#!/panorama/api/DOTAMinimapEvent_t",
    "https://moddota.com/api/#!/panorama/api/DOTAModifierAttribute_t",
    "https://moddota.com/api/#!/panorama/api/DOTAMusicStatus_t",
    "https://moddota.com/api/#!/panorama/api/DOTASlotType_t",
    "https://moddota.com/api/#!/panorama/api/DOTASpeechType_t",
    "https://moddota.com/api/#!/panorama/api/DOTATeam_t",
    "https://moddota.com/api/#!/panorama/api/DOTAUnitAttackCapability_t",
    "https://moddota.com/api/#!/panorama/api/DOTAUnitMoveCapability_t",
    "https://moddota.com/api/#!/panorama/api/DOTA_ABILITY_BEHAVIOR",
    "https://moddota.com/api/#!/panorama/api/DOTA_GC_TEAM",
    "https://moddota.com/api/#!/panorama/api/DOTA_GameMode",
    "https://moddota.com/api/#!/panorama/api/DOTA_GameState",
    "https://moddota.com/api/#!/panorama/api/DOTA_HeroPickState",
    "https://moddota.com/api/#!/panorama/api/DOTA_MOTION_CONTROLLER_PRIORITY",
    "https://moddota.com/api/#!/panorama/api/DOTA_OVERHEAD_ALERT",
    "https://moddota.com/api/#!/panorama/api/DOTA_RUNES",
    "https://moddota.com/api/#!/panorama/api/DOTA_SHOP_TYPE",
    "https://moddota.com/api/#!/panorama/api/DOTA_UNIT_TARGET_FLAGS",
    "https://moddota.com/api/#!/panorama/api/DOTA_UNIT_TARGET_TEAM",
    "https://moddota.com/api/#!/panorama/api/DOTA_UNIT_TARGET_TYPE",
    "https://moddota.com/api/#!/panorama/api/DotaCustomUIType_t",
    "https://moddota.com/api/#!/panorama/api/DotaDefaultUIElement_t",
    "https://moddota.com/api/#!/panorama/api/EDOTA_ModifyGold_Reason",
    "https://moddota.com/api/#!/panorama/api/EDOTA_ModifyXP_Reason",
    "https://moddota.com/api/#!/panorama/api/EShareAbility",
    "https://moddota.com/api/#!/panorama/api/GameActivity_t",
    "https://moddota.com/api/#!/panorama/api/OrderQueueBehavior_t",
    "https://moddota.com/api/#!/panorama/api/ParticleAttachment_t",
    "https://moddota.com/api/#!/panorama/api/PlayerOrderIssuer_t",
    "https://moddota.com/api/#!/panorama/api/PlayerUltimateStateOrTime_t",
    "https://moddota.com/api/#!/panorama/api/SPELL_IMMUNITY_TYPES",
    "https://moddota.com/api/#!/panorama/api/SteamUGCMatchingUGCType",
    "https://moddota.com/api/#!/panorama/api/SteamUGCQuery",
    "https://moddota.com/api/#!/panorama/api/SteamUniverse",
    "https://moddota.com/api/#!/panorama/api/dotaunitorder_t",
    "https://moddota.com/api/#!/panorama/api/modifierfunction",
    "https://moddota.com/api/#!/panorama/api/modifierstate",
]

# 总数
TOTAL_COUNT = len(PANORAMA_API_URLS)  # 48
print(TOTAL_COUNT)